### ISSUE TITLE
Clean up for Business Overview Project

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#108]
## Tasks

 * [x] https://github.com/hypothesis/report/pull/107
 * [x] In https://github.com/hypothesis/h/pull/7718, we should add aliases to the rows?
 * ~Some kind of tagging system etc for Data Tasks?~
    * Would be nice if we could tag files and include or exclude them from the run in Data Tasks
    * I don't think we are doing this
 * [x] Put aggregations into their own namespaces like `lms` and `h` instead of `public`?
    * [x] https://github.com/hypothesis/report/pull/125
    * [x] https://github.com/hypothesis/report/pull/128
    * [x] Move all the reports
    * [x] https://github.com/hypothesis/report/pull/130
    * [x] Check over existing reports again in Metabase
    * [x] https://github.com/hypothesis/report/pull/131

## Notes

We are making a mess in the public schema, because we don't clean it up during a `create_from_scratch`. We should either:

 * Find a way to clean it up
 * Put everything in the report schema like everywhere else (and deal with the fallout in Metabase)

Related to the above, we should probably put LMS things in an "lms" schema, and "h" things in an "h" schema. This avoids any acrobatics in naming around "users", "organizations" and other things shared between the products.

---

Would be nice if we could tag files and include or exclude them from the run in Data Tasks

**Comment by jon-betts** [comment]
I think this is done, but there's no way I didn't break something in Metabase. Doing this was absolutely horrible. I'm glad we did it before we got further, but I really hope we never want to do it again.
