### ISSUE TITLE
Add non sensitive data about courses to existing boards

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#119]
There are multiple locations we want to add data about courses in existing boards. 

We do not need to tackle the requirement to detail teacher emails in this phase. This will allow us to progress quickly with the majority of the work while we work out the details on how to handle sensitive data.

**Note:** For this ticket we're going to skip the summing up and down the hierarchy.

## Tasks

 * [x] Curate and export a combined list of LMS groupings to Report with no sensitive columns
    * https://github.com/hypothesis/lms/pull/4751
    * https://github.com/hypothesis/lms/pull/4755
    * https://github.com/hypothesis/lms/pull/4758
    * https://github.com/hypothesis/lms/pull/4764
    * https://github.com/hypothesis/report/pull/133
 * [x] Add a metric to the business overview showing the total number of courses
 * [x] Add various activity metrics to the course table (or in a course activity table?)
 * [x] Add tables to Organization Overview and Organization Focus boards
 * [x] Bug fixes:
    * https://github.com/hypothesis/lms/pull/4790
    * https://github.com/hypothesis/report/pull/135 - Fix the multiple orgs linked from groups
    * [x] Make use of `lms.organization_group` to replace the joins onto `group_map` (still need to fix [Group Activity By Organization](https://report.hypothes.is/question/108-group-activity-by-organization))
    * [x] Can `group_map` be removed from Report? Yes (https://github.com/hypothesis/report/pull/151)

### Business Overview

 * A metric on the numbers for the board for the total number of courses

### Grouping Overview

 * A table showing groupings with:
     * Name
     * Organization
     * Teacher count (total)
     * User count (total)
     * Assignment count (total)
     * Create date
     * Grouping type (filtered to course by default)
     * Annotation count (within a configurable time period)
     * Launch count (within a configurable time period)
     * Sorted by Annotations DESC
  * The rows should link through to a grouping board

### Organization Focus

 * Kind of the same table as above, but limited to the org
 * Do you want most recently active instead? How would we do this?

## Data required

`groups`

 * We need to add parents
 * We need user / teacher totals
 * Assignment totals
 * Should type be an enum?

`group_activity` 

   * We need to add shared / reply annotation count
   * We need to add launch count
   * We need to do _something_ to roll up counts from sections to course etc. This is probably a separate table?

**Comment by jon-betts** [comment]
Idea for fixing the graph weirdness on:

* https://report.hypothes.is/dashboard/17-group-focus?group_id=us-23982826

Where courses and sub-groupings have misleadingly different graphs. The idea is to graph launches and annotation separately, removing zero rows.
