### ISSUE TITLE
Add a Notion project document for Courses

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#123]
## Tasks

 * [ ]  Create a page in Notion
 * [ ] Add a link to this project board there
 * [ ] Add a link in the side panel of this project board back

# Suggested problem statement

## Problem

A big part of the reason people are interested in active organizations is so they can contact staff there to persue sales opportunites. When our staff are on calls with users it helps to be able to talk specifically about where they have good or poor traction within that organization.

A the moment our metrics are too high level, and don't provide any way to contact people at schools

## Solution

We will integrate information about courses which has:

 * Contact details so staff can reach out
 * More fine grained stats about where activity to form the basis of conversations when reaching out
 * We will introduce a new board which provides as much data as we can on a given "grouping" (like a course or section)
 * This will allow you to navigate to it from organizations, and also to dive into sections from a course for example

## Approach

 * We will expand the existing Report product to include data about courses and metrics for them
 * We will work out a way to access teacher emails in the interface while leaving them at rest in the regions they start in
 * We will act in an 80/20 way to get as much value as quickly as possible (even if we don't replicate every item on the page)
 * We will present working prototypes as quickly as possible
 * Then seek feedback on what, if anything, is required and missing

**Comment by jon-betts** [comment]
I think we know this is busy work to put into Notion. This ticket is probably enough.
