### ISSUE TITLE
Add a new "trailing 12 months" timescale for organization activity

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#169]
There is a concern that looking at this / last academic year is not enough as it may fail to capture the most up to date data.

To get around this, it's been proposed that we also include a trailing 12 months timescale which counts data as close to the last year from the date of calculation. This timescale would constantly update over time.

This is required on the `organization_activity` view, so that billable users can be viewed (amongst others) over the last 12 months.

## Tasks

 * [x] https://github.com/hypothesis/lms/pull/4947
 * [x] https://github.com/hypothesis/report/pull/170
 * [x] Add fields to Hubspot
 * [x] https://github.com/hypothesis/report/pull/177

### Hubspot fields required

`lms_users_last_12_0_months` - Billable users 12-0 months ago
`lms_users_last_24_12_months` - Billable users 24-12 months ago

**Comment by jon-betts** [comment]
Done!
