### ISSUE TITLE
Make organizations searchable by ownership

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#195]
### Tasks V1

 * Update API keys with `crm.objects.owners.read` scope
    * [x] In QA - re-use the one from dev
    * [x] In live - Change the prod one: https://app.hubspot.com/private-apps/6291320
 * https://github.com/hypothesis/devdata/pull/78
 * https://github.com/hypothesis/report/pull/193
 * [x] Add a user centric page with links to organizations and activity
 * [x] Add a team centric page with links to organizations and activity

### Tasks V2

General

 * [x] https://github.com/hypothesis/report/pull/211

LMS User Focus Dash

e.g. https://report.hypothes.is/dashboard/19-prototype-owner-focus-dashboard?owner_id=213113697&timescale=trailing_year&role=user&group_type=course

 * [x] Create one (minimum is showing the name and email)
 * [x] Add courses (with minimum deets)
 * [ ] Find places where a user shows up in teacher reports and link through
 * [ ] Duplicate counting of orgs which have more than one company linking them
 * [ ] Polish pass for names

Team Overview Dash

e.g. https://report.hypothes.is/dashboard/21-prototype-team-overview-dashboard?id=15543479&id=632071

 * [x] Limit to Sales and Success teams
 * [ ] Polish pass for names

Team Focus Dash

e.g. https://report.hypothes.is/dashboard/20-prototype-team-focus-dashboard?team_id=15543479

 * [x] Split the annotation and billable graph into two (over the relevant graphs)
 * This doesn't make any sense. Each team is attached to nearly every record
     * ~Add teacher course info (1 row per teacher, course counts)~
     * ~Add teacher course info (1 row per course, teacher lists)~
 * [x] Allow filtering by company and org in both as a filter
 * [ ] Add something to click on to get to organization dash when the name is blank
 * [ ] Polish pass for names

Owner Focus Dash

 * [x] Split the annotation and billable graph into two
 * [x] Add teacher course info (1 row per teacher, course counts)
 * [x] Add teacher course info (1 row per course, teacher lists)
 * [x] Allow filtering by company and org in both as a filter
 * [ ] Add something to click on to get to organization dash when the name is blank
 * [ ] Group created not showing in results
 * [ ] Polish pass for names

---

I've de-risked the getting things from Hubspot portion of this. We can get the two mentioned types of owners, along with teams. This means we could try to do something with teams, or we could not bother?

~It's worth checking in with @jeremydean to see if a company landing page would be useful or not.~ Yep, I think it is.

There's a few many to many things going on here, so we might need some cross reference tables or array columns:

 * Users can be in multiple teams
 * Orgs have multiple companies

So it might be convienent to have something like `organization_owners` with:

 * `organisation_id`
 * `success_owner_ids`
 * `company_owner_ids`
 * `team_ids`

Nope! https://github.com/metabase/metabase/issues/2974 - Metabase doesn't really work with array fields...

### Aha! We can use Metabase for mockups!

- https://report.hypothes.is/dashboard/20-prototype-team-focus-dashboard?team=Success
- https://report.hypothes.is/dashboard/19-prototype-owner-focus-dashboard?owner=Bob%20Smith

----

### User story

> As a member of the success or sales team, I would like to conveniently see all organizations which are assigned to me.
> 

### Background

Our sales and success staff are grouped into teams:

- Sales Team 1
    - Member 1
    - Member 2
- Success Team 1
    - Member 3
    - Member 4

Companies are allocated to individual members, not teams (although the link is implicit). Each company has one member from each kind of team stored in fields on the record:

- Sales team member: “Company owner”
- Success team member: “Success owner”

### Initial idea for a solution

Have a separate table / column for company owner and success owner and make it searchable on the organization overview page.

### Priority (High)

This would be very beneficial for our users as this is currently a massive pain.

### Effort Estimate (Medium)

We don’t have the data we need for this, but assuming it’s readily available from the Hubspot API (we’d want to check this) then getting this out and combining it shouldn’t be very hard. This should be investigated if we want to de-risk this, as this is kind of a big un-get-roundable hurdle if we can’t pull these values.

This will be more effort than the single report items above, but each step should be more straight forward once we have the info. 

### User story

> As a team manager I would like to be able to compare activity metrics across organizations owned by the different staff members in my team. This would let me spot if someone is doing well or badly compared to their peers.
> 

### Background

If you are a team leader you need to be able to compare performance of the various team members. This implies a view where all, and only, your team members are visible.

I do not know how this is done currently.

This implies you can see:

- The metrics you care about
- The relevant team member names

It strikes me this might be better grouped by user than org? It would be good if it wasn’t as this is harder for us.

### Initial idea for a solution

Have a separate table / column for company owner and success owner and make it searchable on the organization overview page.

The team leader can pick multiple values for user until they have filled out their team.

The table must display the users so they can know who is who.

### Priority (Medium)

You might get this for free as result of the above, but as there are many more users than managers it seems like the above is probably more broadly beneficial?

### Effort Estimate (Low / None)

We have to make sure we show the relevant user in the table, and if that’s enough, then this is really very little effort. If something more fancy is required (like aggregating values by user) this could be more involved. We’d need a bit more detail.

**Comment by nairiboo** [comment]
Feedback from Loree that we can close
