### ISSUE TITLE
Operation: Tidy Up

### ISSUE THREAD

**Issue by indigobravo** [hypothesis/report#21]
### Task

We created a number of temporary resources that were used for general experiments whilst developing the reporting service MVP. These need to be removed.

- [x] Temp VPC One
- [x] Temp VPC Two
- [x] Temp VPC Three
- [x] Remove temp-business-intel-* RDS instances
- [x] Metabase Internal can be removed from US and CA
- [ ] Maybe others...

### Outcome

The temporary resources we created will have been removed.

**Comment by indigobravo** [comment]
The temp-business-intel-* RDS instances are still being used, and can not be removed at this stage. However, to help keep a handle on costs instance types and I/O performance has been reduced to much lower levels.

If needed we can increase resources, but what we have should be good for development. It is not going to be good for performance testing, but I have a feeling we have got passed that point.
