### ISSUE TITLE
Summaries of annotation types for an organization

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#231]
For:

 * https://github.com/hypothesis/report/issues/226

## Why are we doing it?

I _think_ this is about quickly orienting staff about the size an nature of a customer when looking at their stats.

## What are we doing

We should show some pie charts at the top of the assignment page which summaries various information about annotation types.

## Tasks

 * [x] Add fake pie charts
 * [ ] Resolve the naming issue around "Annotation"
 * [x] https://github.com/hypothesis/h/pull/7985
 * [x] https://github.com/hypothesis/h/pull/8003
 * [x] Run the migration
 * [x] Create `group_annotation_types` with summaries of types (including private / shared as a different column)
    * We'll need this later
 * [x] Create `organization_annotation_types` with summaries of types (including private / shared as a different column)
 * [x] A graph showing annotation type: "Annotation" / reply / page-note / highlight per time period
 * [x] A graph showing annotation count by student / teacher by time period (Student or user?)

### Annotation type

In this context everything is a sub-type of "annotation". Annoyingly one of these sub-types is "annotation" which is confusing. We might have to disambiguate this, as we use the term in both ways and it will cause confusion.

| Type | Text | Anchoring | Root | Notes |
|---------|-------|-----------------|---------|----------|
| **Annotation** | Yes | Yes | Yes |
| **Highlight**     | No | Yes | Yes |
| **Page note**   | Yes | No | Yes |
| **Reply**           | Yes | No | No |
| n/a*                     | No | No | Yes | This is how a page note starts before you are forced to add text
| n/a *                    | Yes | Yes | No | This is a reply, but with anchoring which the system does not do
| n/a*                     | No | Yes | No | This is a reply, but with anchoring which the system does not do + missing text
| n/a*                     | No | No | No | This is how a reply starts before you are forced to add text

*The items marked `n/a` should not be allowed by the system

### Sharing status

 * Shared - Viewable by members of the group
 * Private - Viewable by authors only

This does not imply anything about the group itself, which might be shared or private as well

### Author type

Only in an LMS context, we could consider if the author was:

 * A teacher
 * Not a teacher

We might save ourselves some headaches by skipping whether the user is a teacher in _this_ context, or just a teacher in _a_ context.

### Interaction type

If you are interested in how people are interacting with each other you might want to look at this in another way:

* Items at the root level with no replies
* Items at the root level with replies
* Replies

There are many variations on this you might consider. For example replies with replies etc. You could express this as:

* Stubs - Root items without replies
* Openers - Root items with replies
* Continuations - Replies with replies
* Closers - Replies with no replies

_However:_ I'd really suggest having a think about better metrics. What these are nudging at, but not giving you is an idea of how long conversations go on for, or if they happen at all. Why not explicitly track this?

This would be a _thread based_ rather than _annotation based_ approach. And might give metrics like:

 * Threads / group
 * Annotations / thread
 * Thread length distribution (10 were 1 long, 3 were 2 long, 5 were 5 long etc.)
 * Unique participants per thread
 * Some combination of the above (looking for long threads with many participants) - I propose we call this metric "banter"
 
### Combinations of types

You can freely combine most types with each other with the exception of interaction type + annotation type, which has one caveat:

  * Annotations can be deleted
  * If an annotation is deleted we don't know what kind it used to be
  * So some replies will be replies to missing annotations and we won't be able to say if it was a highlight etc.
  * So "reply to highlight" is a thing, but so would "reply to deleted / mystery"

## Storage method

This is all a bit iffy. There are two major ways to store the data:

| Group Id | Replies | Annotations | Page Notes | Highlight | Shared | Private |
|---------------|-------------|-----------------|--------------------|--------------|-------------|-----------|
| 2234525| 234 | 500 | 23 | 16 | 420 | 80 |

This is similar to how we are currently doing `annotation_group_counts`. This is good for 
tabular presentation.

Or we can do this:

| Group Id | Annotation Type | Shared | Count |
|---------------|--------------------------|------------|----------|
| 2234525 | Reply | True | 230 |
| 2234525 | Reply | False | 4 |
| 2234525  | Annotation | True | 400 
| 2234525  | Annotation | False | 400 
| 2234525  | Page Note | True | 10
| 2234525  | Page Note | False |  6
| 2234525  | Highlight | True | 17
| 2234525  | Highlight | False |  4

This is much better for pie charts, and is more versatile (we can ask more questions). In the summary above, we can tell you that there are X private things, but not what types they are.

## Effort estimate

 * A pain potentially (requires a big re-index job to work)

The annotation re-indexing might take around 1-2hrs. We would only need to do it once, _if we got it right_. But we have no development environment for this, so we'd really be guessing. If we make mistakes, it's going to be painful. We also really want to get our definitions right, as we can't cheaply change them.
