### ISSUE TITLE
Try using views to control access to underlying tables

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#255]
# Tasks

 * [x] https://github.com/hypothesis/h/pull/8035
 * [x] https://github.com/hypothesis/lms/pull/5548
 * [x] https://github.com/hypothesis/report/pull/257
 * [x] https://github.com/hypothesis/lms/pull/5549
 * [x] https://github.com/hypothesis/h/pull/8036
 * [x] https://github.com/hypothesis/lms/pull/5550
 * [x] https://github.com/hypothesis/h/pull/8037

## Description

The reporting system has it's own schema in LMS and `h` where the majority of views which are exported up the chain exist. These form a contract of sorts, where you can change how the views are calculated as long as the output remains the same shape.

This isn't true for some tables which are read from the main schema, which we would be sensitive to should they change. Our tables don't change much, but it might be a nice idea to have thin proxy views around these tables.

These views could specify the columns which are read from upstream consumers, and provide a consumer contract of sorts.

When this is done:

 * No tables outside of the report schema should be read from other services
 * You could, if you chose, maintain these interfaces while making changes internal to the product
 * You could also change reporting to read the new tables if that made sense of course
 * There will be a slight execution and maintenance overhead to working this way

### Tables read from the main schema

Report -> LMS:

  * `organization`

LMS -> h:

 * `group`
 * `user`
 * `user_group`
