### ISSUE TITLE
Filter customers on user dashboards by actual customers

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#258]
>... see if it is possible to pull any additional properties from HS so that our individual dashboard’s in Metabase only show companies that are actual customers. As an example, on my [personal dashboard](https://report.hypothes.is/dashboard/19-prototype-owner-focus-dashboard?owner_id=51433448&timescale=trailing_year&role=user&group_type=course) it shows all companies where I am the Success Owner but I actually only work with companies that are customers. Is it possible to refine this pull so that it only includes customers? Some properties that could potentially help with this are:

Customer Lifecycle Stage = Customer
Current Services Start  / Current Services End

From: Becky George

We have services start and end, but it's difficult to filter to (now) on them. We can pull the extra field and create a combined "Active" field in SQL

## Tasks

 * [x] https://github.com/hypothesis/report/pull/259
 * [x] Add filters to the owner focus dashboard
 * [x] Try and limit each view to make use of it
 * [x] https://github.com/hypothesis/report/pull/260
