### ISSUE TITLE
SQL task runner as a library

### ISSUE THREAD

**Issue by marcospri** [hypothesis/report#47]
## Tasks

 * [x] Fix task runner when there's no queries in a file
    *  https://github.com/hypothesis/h/pull/7690
 * [x] Dry run capability for SQL task runner
    * https://github.com/hypothesis/report/pull/72
 * [x] Can we run python files as part of the run? - This would allow us to do the Hubspot refresh in place
    * https://github.com/hypothesis/report/pull/53
 * [x] Investigate: Auto format and check formatting of sql files
    * Discarded after  https://github.com/hypothesis/lms/pull/4656
 * [x] When the runner is feature complete in Reports, move it to a library
    * [x] https://github.com/hypothesis/data-tasks/pull/4
    * [x] https://github.com/hypothesis/report/pull/87
    * [x] Replace the code in LMS
    * [x] Replace the code in H

## Ideas for another day?

 * What about building in a retry?
 * More full tag system to allow partial runs (mostly to avoid the annoying bits of the Hubspot update)
