### ISSUE TITLE
Add monitoring integration to the report project

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#48]
## Tasks:

We aren't trying to put this in Metabase are we?

Sentry:

 * [x] Create a new Sentry DSN for Report
 * [x] Add Sentry environment variables to AWS for Report
 * [x] https://github.com/hypothesis/report/pull/64

New Relic:

 * ~Create a new New Relic API key for Report~ It's the same key for all apps
 * [x] Add New Relic environment variables to AWS for Report
 * [x] Add New Relic integration to the SQL running tasks
     * [x] https://github.com/hypothesis/report/pull/62
     * [x] https://github.com/hypothesis/lms/pull/4653
     * [x] https://github.com/hypothesis/h/pull/7708
 *  [x] Fixes:
     * [x] https://github.com/hypothesis/report/pull/78

## Notes

The environment variables used for this in LMS are:

```
NEW_RELIC_APP_NAME=report
NEW_RELIC_ENVIRONMENT=prod
NEW_RELIC_LICENSE_KEY=...

SENTRY_ENVIRONMENT=prod
SENTRY_DSN=...
```

FYI: https://docs.sentry.io/platforms/python/

**Comment by jon-betts** [comment]
This is all done, but I've not actually seen it run in Report yet, because our deploy failed. Once that happens, I think we are done.

**Comment by jon-betts** [comment]
I don't see anything in New Relic, but it being what it is, for all I know this is expected. If we aren't currently trying to send any metrics, I'm going to call this good enough for now.

**Comment by jon-betts** [comment]
Done again?
