### ISSUE TITLE
Limit access to tables to only those which are required

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#49]
We use the postgres user which seems to be a superuser and that masks all the permissions issues we are finding while deploying the FDW connections locally, which makes this hard to test.

## Tasks

 * [x] Try to closely mimic permissions structure in development DBs
    * How would we do this? I'm not sure what mechanism we have to add users as the DB is setup?
    * Normally we'd call our own DB init stuff, but we don't have any here as we aren't an app?
    * One option is https://hub.docker.com/_/postgres/ "Initialisation scripts"
    * Or: https://github.com/hypothesis/cookiecutters/pull/93
    * In the end we went with a new task to add users in dev and changed the FDW details to match
 * [x] Apply more restrictions in our permission granting in LMS + H
   * [x] https://github.com/hypothesis/h/pull/7713
   * [x] https://github.com/hypothesis/lms/pull/4665
   * [x] https://github.com/hypothesis/report/pull/86

## Required access

[LMS to H](https://github.com/hypothesis/lms/blob/main/lms/sql_tasks/tasks/report/create_from_scratch/00_schema/03_create_fdw_schema.sql#L22)

 * `public`
    * `user_group`
    * `user`
    * `group`
 * `report`
   * `authorities`
   * `annotation_group_counts`
   * `annotation_user_counts`

[Report to LMS](https://github.com/hypothesis/report/blob/main/report/sql_tasks/tasks/report/create_from_scratch/00_schema/04_create_fdw_schema_lms.jinja2.sql#L25)

 * `public`
   * `organization`
 * `report`
    * `organization_activity`

## Current access

* H currently grants permission to the FDW users here:
   * https://github.com/hypothesis/h/blob/main/h/sql_tasks/tasks/report/create_from_scratch/05_grant_permissions/01_grant_schema.jinja2.sql
   * Everything in `report`
   * `user_group`, `user` and `group` in `public`
   * Which seems about right
* LMS currently grants permission to the FDW users here:
   * https://github.com/hypothesis/lms/blob/main/lms/sql_tasks/tasks/report/create_from_scratch/05_grant_permissions/01_grant_schema.jinja2.sql
   * Everything in `report`
   * Only `organization` in `public`
   * This seems about right?

The FDW users are:

 * In H: `lms-qa`, `lms-prod` (as there's a shared DB for QA)
 * In LMS: `report-prod`
 
## Is anything missing?

I'm not sure we want to lock this down much more than we do now. The options seem to me to be:

 * Limit the items in `report` to those that are required. Seems little reason not to do this, it's quite easy?
 * Do we want to limit Metabase in anyway? I'm guessing not? As it's what we use to explore data

**Comment by jon-betts** [comment]
I think we are all done here.
