### ISSUE TITLE
Rework report aggregation and models in Metabase

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#51]
Some various miscellaneous tidy ups

## Tasks

 * ~Company `lms_organization_id` should be `organization_public_id`~
     *  ~https://github.com/hypothesis/report/pull/60~
     * ~Remove anything built on this in Metabase~
     * Came to the conclusion this is kind of worse
 * [x] Names from Hubspot should be on the `organizations` table in the DB
    * [x] https://github.com/hypothesis/report/pull/61
    * [x] https://github.com/hypothesis/report/pull/80
    * [x] Remove anything built on this in Metabase
    * [x] https://github.com/hypothesis/report/pull/83
 * [x] Review and try and cut down the number of things we have in Metabase
 * [x] Work over graph axis names etc (the defaults aren't great)
 * [x] Investigate rogue rows in Organization Activity with no region (wat?)
    * It's a dodgy join, hopefully fixed by: https://github.com/hypothesis/report/pull/83
    * There's more. We have quite a few items with NULL org ids in LMS - I'm not sure this is even a bug or not?
   * It is a bug to include them in the org activity table though
   * I've moved this to a separate ticket: https://github.com/hypothesis/lms/issues/4663
 * [x] Think about organizational principal in Metabase (by type, or by report? etc.)
    * Models in their own directory
    * A directory for "Questions" organized by dashboard
    * A shared directory in "Questions" for items used by more than one dashboard
