### ISSUE TITLE
Create a project board for: Business Overview MVP

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#66]
We are looking to replicate the type of high-level business overview provided by the current [metrics for the board](https://metabase.hypothes.is/dashboard/49-key-metrics-overview-for-the-board). This means:

 * Creating some more detailed object themed boards (users / annotations) for detailed dives
 * Creating a high-level summary board
 * Replacing the feed to Slack

We can do better than the existing board by being:

 * Global (including Canada)
 * Faster
 * More accurate (many items on the boards are approximations)
 * More interactive (choosing facets etc.)

This will provide more complete and compelling information, and remove one pillar which requires the existing system to stick around.

## Tasks

 * [ ] ~Create a project outline in Notion~ (I was going to do this, but I can't figure Notion out. I've made a ticket here: https://github.com/hypothesis/report/issues/89)
 * [x] Create a project board
 * [x] Identify any questions we can foresee to resolve before the project gets going

### Business Overview

Like this: https://metabase.hypothes.is/dashboard/49-key-metrics-overview-for-the-board

 * 6 monthly MAU (monthly active user) CMGR (cumulative monthly growth rate)
    * Count now vs. count 6 months ago, as a percentage
 * 12 monthly MAU (monthly active user) CYGR (cumulative yearly growth rate)
    * Count now vs. count 12 months ago, as a percentage
 * ... TBA ...

Not (for now) covering metrics around:

 * Groups (courses etc.)
 * Documents / URLs
 * Account creation - because this is a proxy for differential user counts

### H - Users overview

 * Cumulative users over multiple time periods
 * Exact users over multiple time periods
 * Total users in authority

### H - Annotations overview

 * Cumulative annotations over multiple time periods
 * Exact annotations over multiple time periods
 * Total annotations in authority

### Slack output dashboard

 * Put together highlights from the business overview
 * Export them to the `#metrics` channel in Slack
 * Remove the existing integration from Metabase (https://metabase.hypothes.is/dashboard/62-slack-update-topline-stats)

### LMS - Organizations overview

 * Update the sortable table to include launches

### From LMS

 * Expand organization activity to have launches as an activity metric

### From H

_We'd probably do the annotations by updating our group activity materialized view to distinguish by the different annotation types._

Annotations:

 * Of type:
   * Existing
   * Shared (this doesn't depend on group status at all)
   * Private
   * Page note ones
 * By:
   * Authority        
   * Time period (all time /  calendar year /  academic year / semester / month)
 * As:
   * Count in the period
   * Cumulative value

Users:

 * Of type:
    * Existing
    * Annotating
 * By:
   * Authority        
   * Time period (all time /  calendar year /  academic year / semester / month)
 * As:
   * Count in the period
   * Cumulative value

**Comment by jon-betts** [comment]
I think this is done now. We have a board.
