### ISSUE TITLE
Find out how we can merge aggregated data for global reports

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#7]
We want to be able to present high level data which provides oversight of all our customers regardless of which region they are in.

### The types of things we are curious about

 * How many annotations have we made in total?
 * Which of our customers annotate the most?
 * Who has the most active users / or the least?

### Requirements

* We need to do this in such a way as we do not breach any data protection rules for the region
* It needs to be fast to access
* It can be up to a day out of date
* Adding a new region can't be a huge amount of manual work (but a small amount is acceptable as we won't do it very often).
* It does have any horrible security implications
* Is resilient to individual regions being down

## Assumptions

 * [ ] Aggregated data about organizations is safe to transport out of region regardless of the specifics of data protection rules
 * [ ] Our own metadata about users is safe to transport (the organization name etc.)
 * [ ] We can use FWD + materialized views to create merged materialized views that will work for this
 * [ ] ... or there's a Metabase way
 * [ ] ... or we can do this with some kind of push?
 * [ ] Whatever we do will be easy to maintain when we add new reports or regions (a smaller number of underlying models?)
     * If we are doing our own materialized views this seems easier than Metabase stuff? We could have templated SQL or something

## Tasks

 * We should get an empty DB in Canada to try and to join it across regions
    * We are using an empty DB because this ticket is not concerned with the legal aspects
    * To be safe because we don't want to do something with real data we later find out isn't allowed
    * We will need to put in some example data to sync
 * We should be able to re-use the DBs we already have for this work
 * We should document the different ways we came up with and pros and cons

**Comment by indigobravo** [comment]
I feel the operational elements of this issue have been satisfied. Technically, we have the means to:

> aggregate data for global reports

Details have been written up against: [Proposed solution for internal global reports](https://www.notion.so/Proposed-solution-for-internal-global-reports-6b48e251861842ca8b2c7a6ea76c15fd#b7cb30ee798f4b1bb947eb64de19a90e)
