### ISSUE TITLE
Add a Notion project document for the Business Overview

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#89]
## Tasks

 * [ ]  Create a page in Notion
 * [ ] Add a link to this project board there
 * [ ] Add a link in the side panel of this project board back

# Suggested problem statement

## Problem

We use the [metrics for the board dashboard](https://metabase.hypothes.is/dashboard/49-key-metrics-overview-for-the-board) in the existing Metabase to provide an overview of various high level business outcomes, but:

 * For performance reasons many items are approximations
 * Some items are not calculated at all, but are fixed numbers
 * Some rely on the old `analytics-db` and are therefore unreliable
 * No data from Canada is included
 * There is little or no ability to explore or filter the data

## Solution

We will recreate a new board which presents similar data in the Report project. This will be better than the existing board by:

 * Including Canada
 * Using exact numbers rather than estimates or fixed values
 * Be more reliable
 * Updated nightly
 * More responsive (each report in the page should return in <= 2s)
 * More hands on controls (e.g. filters)
 * More ability to explore

## Approach

 * We will expand the existing Report product
 * We will act in an 80/20 way to get as much value as quickly as possible (even if we don't replicate every item on the page)
 * We will present working prototypes as quickly as possible
 * Then seek feedback on what, if anything, is required and missing

**Comment by jon-betts** [comment]
I think we know this is busy work to put into Notion. This ticket is probably enough.
