### ISSUE TITLE
Add an "H - Users overview" dashboard

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#90]
**Note!** - I think this is more the user area of an "Authority Overview" dashboard

## Tasks

 * [x] https://github.com/hypothesis/h/pull/7717
 * [x] https://github.com/hypothesis/report/pull/97
 * [x] https://github.com/hypothesis/report/pull/101
 * [x] Create dashboard

## Reports

Inspired by: https://metabase.hypothes.is/dashboard/49-key-metrics-overview-for-the-board

Reports we need to enable on the business overview board:

 * MAU 6mo CMGR 
 * MAU last full month
 * Monthly annotating users, by month (we can be more fancy than just month)
 * Registering users by intervals
 * Daily users
 * Total registered users (in authority)

## Data required

Users:

 * Of type:
    * Existing
    * Annotating
 * By:
   * Authority        
   * Time period (all time /  calendar year /  academic year / semester / month)
 * As:
   * Count in the period
   * Cumulative value
