### ISSUE TITLE
Add an "H - Annotations overview" dashboard

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#91]
**Note!** - I think this is more the annotation area of an "Authority Overview" dashboard

## Tasks

 * [x] https://github.com/hypothesis/h/pull/7718
 * [x] https://github.com/hypothesis/report/pull/98 - merged by mistake
 * [x] https://github.com/hypothesis/report/pull/99
 * [x] https://github.com/hypothesis/report/pull/104

## Reports

Inspired by: https://metabase.hypothes.is/dashboard/49-key-metrics-overview-for-the-board

Reports we need to facilitate on the main business overview board

* Cumulative annotations over multiple time periods
* Total annotations
* Annotations per month
* Daily annotations

## Data required

_We'd probably do the annotations by updating our group activity materialized view to distinguish by the different annotation types._

Annotations:

 * Of type:
   * Existing
   * Shared (this doesn't depend on group status at all)
   * Private
   * Page note ones?
 * By:
   * Authority        
   * Time period (all time /  calendar year /  academic year / semester / month)
 * As:
   * Count in the period
   * Cumulative value

**Comment by jon-betts** [comment]
I haven't really put much on the authority dash, but the main one looks quite full.
