### ISSUE TITLE
Add launches to "LMS - Organizations overview"

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#92]
## Reports

Inspired by: https://metabase.hypothes.is/dashboard/49-key-metrics-overview-for-the-board

We will need to enable the following in the business dashboard:

 * LTI launches ever (single fixed number)
 * LTI launches last 30 days
 * Top schools by launches <- Hang on, is this an alternative measure of "active" users?
 * Daily (!) LTI launches - Hopefully weekly is fine

## Tasks

 * [x] https://github.com/hypothesis/lms/pull/4676
 * [x] https://github.com/hypothesis/report/pull/96
 * [x] https://github.com/hypothesis/lms/pull/4679
 * [x] https://github.com/hypothesis/report/pull/100
 * [x] https://github.com/hypothesis/report/pull/103
 * [x] Update the sortable table to include launches
 * [x] Add to the big dashboard too
