### ISSUE TITLE
Add a Slack output dashboard

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#93]
## Tasks

* [ ] Put together highlights from the business overview
* [ ] Export them to the #metrics channel in Slack
* [ ] Remove the existing integration from Metabase (https://metabase.hypothes.is/dashboard/62-slack-update-topline-stats)
