### ISSUE TITLE
Replace Sparky with a task in Report

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/report#95]
## Tasks

 * [x] https://github.com/hypothesis/report/pull/81
 * [x] https://github.com/hypothesis/report/pull/106
 * [x] https://github.com/hypothesis/sparky/pull/201
 * [x] Move any interesting or useful docs out of Sparky to Report (some SQL tutorials would be a good fit for example)
     * https://github.com/hypothesis/report/pull/109
 * [x] Clear up the various pieces of infrastructure
    * [x] Remove the Sparky keys from SSM
    * [x] Remove Dead Man's Snitch monitoring
    * [x] Remove entries permitting the EMR security group access to RDS resources (US)
    * [x] Remove terraform code permitting the EMR security group access to RDS resources (CA)
    * [x] Remove S3 logging directories
    * [x] Remove papertrail config
    * [x] Remove self-hosted GitHub runner EC2
    * [x] Remove sparky user
    * [x] Remove security groups, policies and ancillary AWS configuration related to the runner. 
    * ~~Remove custom log to papertrail Ansible role. It was only being used by the runner.~~
    * [x] Remove the Sparky API keys from Hubspot
    * [x] What else... ?
        - For the life of me I can not think of anything else that should obviously be removed, but I am sure we are going to be finding artefacts of Sparky for a while...
 * [x] Archive the Sparky repo

**Comment by indigobravo** [comment]
We are  good to go on this. I have scheduled the work to happen the week starting: 2023-01-09

**Comment by indigobravo** [comment]
Attaching for future reference... This is a custom IAM policy once bound to the self-hosted github running Sparky used.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "elasticmapreduce:DescribeStep",
                "elasticmapreduce:ListClusters",
                "elasticmapreduce:AddJobFlowSteps",
                "elasticmapreduce:RunJobFlow"
            ],
            "Resource": "*",
            "Condition": {
                "IpAddress": {
                    "aws:SourceIp": "52.8.94.67/24"
                }
            }
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "elasticmapreduce:DescribeCluster",
                "elasticmapreduce:AddTags",
                "elasticmapreduce:TerminateJobFlows"
            ],
            "Resource": [
                "arn:aws:elasticmapreduce:us-west-1:964867326460:cluster/*",
                "arn:aws:elasticmapreduce:ca-central-1:964867326460:cluster/*"
            ],
            "Condition": {
                "IpAddress": {
                    "aws:SourceIp": "52.8.94.67/24"
                }
            }
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": "iam:PassRole",
            "Resource": [
                "arn:aws:iam::964867326460:role/EMR_EC2_DefaultRole",
                "arn:aws:iam::964867326460:role/EMR_DefaultRole"
            ],
            "Condition": {
                "IpAddress": {
                    "aws:SourceIp": "52.8.94.67/24"
                }
            }
        },
        {
            "Sid": "VisualEditor3",
            "Effect": "Allow",
            "Action": [
                "rds:AddTagsToResource",
                "rds:DescribeDBSnapshots",
                "rds:CreateDBSnapshot",
                "rds:DeleteDBSnapshot"
            ],
            "Resource": [
                "arn:aws:rds:us-west-1:964867326460:db:h-read02-pg11",
                "arn:aws:rds:ca-central-1:964867326460:db:prod-ca-central-1-db-replica",
                "arn:aws:rds:us-west-1:964867326460:snapshot:sparky-*",
                "arn:aws:rds:ca-central-1:964867326460:snapshot:sparky-*"
            ],
            "Condition": {
                "IpAddress": {
                    "aws:SourceIp": "52.8.94.67/24"
                }
            }
        },
        {
            "Sid": "VisualEditor4",
            "Effect": "Allow",
            "Action": [
                "rds:AddTagsToResource",
                "rds:DeleteDBSubnetGroup",
                "rds:ListTagsForResource",
                "rds:RestoreDBInstanceFromDBSnapshot",
                "rds:CreateDBInstance",
                "rds:DescribeDBInstances",
                "rds:ModifyDBInstance",
                "rds:CreateDBSubnetGroup",
                "rds:DeleteDBInstance"
            ],
            "Resource": [
                "arn:aws:rds:us-west-1:964867326460:db:sparky-*",
                "arn:aws:rds:ca-central-1:964867326460:db:sparky-*",
                "arn:aws:rds:us-west-1:964867326460:snapshot:sparky-*",
                "arn:aws:rds:ca-central-1:964867326460:snapshot:sparky-*",
                "arn:aws:rds:us-west-1:964867326460:subgrp:sparky-*",
                "arn:aws:rds:ca-central-1:964867326460:subgrp:sparky-*"
            ],
            "Condition": {
                "IpAddress": {
                    "aws:SourceIp": "52.8.94.67/24"
                }
            }
        },
        {
            "Sid": "VisualEditor5",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::hypothesis-emr-us-west-1/*",
                "arn:aws:s3:::hypothesis-emr-ca-central-1/*",
                "arn:aws:s3:::hypothesis-emr-us-west-1",
                "arn:aws:s3:::hypothesis-emr-ca-central-1"
            ]
        },
        {
            "Sid": "VisualEditor6",
            "Effect": "Allow",
            "Action": [
                "ssm:PutParameter",
                "ssm:GetParameter"
            ],
            "Resource": [
                "arn:aws:ssm:us-west-1:964867326460:parameter/sparky/*",
                "arn:aws:ssm:ca-central-1:964867326460:parameter/sparky/*"
            ],
            "Condition": {
                "IpAddress": {
                    "aws:SourceIp": "52.8.94.67/24"
                }
            }
        }
    ]
}
```

**Comment by indigobravo** [comment]
#### Remove custom log to papertrail Ansible role. It was only being used by the runner.

I have removed this tasks from the list above...

Our old ansible code is due to be replaced. I see little point in updating what we have because it is all going to get removed.

**Comment by indigobravo** [comment]
Thinking this can now be closed. I suspect 99% of the configuration we implemented for Sparky has been removed from our various services. However, I have no doubt we will be finding artefacts for some time. Those can be tided up as we find them.
